### ISSUE TITLE
help running migec-1.2.1a

### ISSUE THREAD

**Issue by djoconnell** [mikessh/migec#12]
I am great admirer of this work and also not well versed in programming, but I managed to get to the CdrBlastBatch step of my mouse TCR analysis when I run into problem.

It seems to get through some of the CdrBlast for the first sample because it creates a new folder "TSO_Well_92_R12.t3.cf.fastq.gz-cdrblast-6314a4a9-febf-48d1-a6ae-3fc821910c14" in the assemble directory.

Thank you very much and apologies if this is not the correct forum for contact help.

Best regards

[gmc6a-2ec:~/Desktop/TCRb_MIGDEC] dconnell% java -Xmx8G -jar migec-1.2.1a.jar CdrBlastBatch --sample-metadata 2015_06_18_Listeria_Metadata.txt checkout/ assemble/ cdrblast/
Jun 25, 2015 7:36:57 PM org.codehaus.groovy.runtime.m12n.MetaInfExtensionModule newModule
WARNING: Module [groovy-all] - Unable to load extension class [org.codehaus.groovy.runtime.NioGroovyMethods]
Executing com.milaboratory.migec.CdrBlastBatch --sample-metadata 2015_06_18_Listeria_Metadata.txt checkout/ assemble/ cdrblast/
[Thu Jun 25 19:36:58 EDT 2015 com.milaboratory.migec.CdrBlastBatch] Running CdrBlast for raw and assembled data..
Executing com.milaboratory.migec.CdrBlast --same-sample -R TRB -S MusMusculus -a -q 30" /Users/dconnell/Desktop/TCRb_MIGDEC/assemble/TSO_Well_92_R12.t3.cf.fastq.gz cdrblast/TSO_Well_92.asm.cdrblast.txt
[Thu Jun 25 19:36:58 EDT 2015 com.milaboratory.migec.CdrBlast] Loading TRB Variable and Joining segment data
[Thu Jun 25 19:36:58 EDT 2015 com.milaboratory.migec.CdrBlast] Generating BLAST database for TRB V
[Thu Jun 25 19:36:58 EDT 2015 com.milaboratory.migec.CdrBlast] Generating BLAST database for TRB J
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/milaboratory/migec/dalign/SegmentSearcher : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at com.milaboratory.migec.CdrBlast.run(CdrBlast.groovy:299)
	at com.milaboratory.migec.CdrBlast$run.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at com.milaboratory.migec.CdrBlastBatch$run.call(Unknown Source)
	at com.milaboratory.migec.Util.run(Util.groovy:36)
	at com.milaboratory.migec.Util$run.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
	at com.milaboratory.migec.CdrBlastBatch$_run_closure8_closure14.doCall(CdrBlastBatch.groovy:298)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:272)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:909)
	at groovy.lang.Closure.call(Closure.java:423)
	at groovy.lang.Closure.call(Closure.java:439)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.callClosureForMapEntry(DefaultGroovyMethods.java:4242)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:1402)
	at org.codehaus.groovy.runtime.dgm$151.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:271)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at com.milaboratory.migec.CdrBlastBatch$_run_closure8.doCall(CdrBlastBatch.groovy:248)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:272)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:909)
	at groovy.lang.Closure.call(Closure.java:423)
	at groovy.lang.Closure.call(Closure.java:439)
	at org.codehaus.groovy.runtime.IOGroovyMethods.withWriter(IOGroovyMethods.java:1134)
	at org.codehaus.groovy.runtime.ResourceGroovyMethods.withPrintWriter(ResourceGroovyMethods.java:1877)
	at org.codehaus.groovy.runtime.dgm$877.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:271)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at com.milaboratory.migec.CdrBlastBatch.run(CdrBlastBatch.groovy:228)
	at com.milaboratory.migec.CdrBlastBatch$run.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at com.milaboratory.migec.Util.run(Util.groovy:36)
	at com.milaboratory.migec.Util$run.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
	at com.milaboratory.migec.Migec.run(Migec.groovy:103)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1085)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:909)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:901)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:884)
	at org.codehaus.groovy.runtime.InvokerHelper.runScript(InvokerHelper.java:406)
	at org.codehaus.groovy.runtime.InvokerHelper$runScript.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
	at com.milaboratory.migec.Migec.main(Migec.groovy)

**Comment by mikessh** [comment]
Hello! 

Thanks for you feedback! The "Unsupported major.minor version 51.0" error generally comes from using wrong java version, see http://stackoverflow.com/questions/10382929/how-to-fix-unsupported-major-minor-version-51-0-error

Can you check the version of Java that you are using with `java -version`? I would recommend to install [JRE 1.8](http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html) and see if it runs fine. Please let me know if the issue is resolved.

**Comment by djoconnell** [comment]
Thank you!

Works beautifully now.  MIGEC calls clones from ~23% of my wells.  I need to boost the RNA-seq library quality a bit more.  Thank you again for your help and for creating the immune repertoires sequencing analysis pipelines.

Best regards,

Dan
